# Generated by Django 5.2.7 on 2025-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('SIM', 'Simple'), ('DOB', 'Doble'), ('SUI', 'Suite'), ('FAM', 'Familiar')], default='DOB', max_length=3)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_huespedes', models.IntegerField(default=2)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
