# Generated by Django 5.2.7 on 2025-10-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
