# Generated by Django 5.2.7 on 2025-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_huesped_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
